# MAPPO parameters

# Detailed explanation for each hyper parameter can be found in ray/rllib/agents/ppo/ppo.py

# Default Parameter
# algo_args:
#   use_gae: True
#   lambda: 1.0
#   kl_coeff: 0.2
#   batch_episode: 10
#   num_sgd_iter: 5
#   vf_loss_coeff: 1.0
#   lr: 0.0005
#   entropy_coeff: 0.01
#   clip_param: 0.3
#   vf_clip_param: 10.0
#   batch_mode: "complete_episodes"
#   num_samples: 1                      # set to other only during tuning
#   lr_schedule: null                   # [[timestamp, lr], ...]
#   entropy_coeff_schedule: null        # [[timestamp, entropy], ...]
#   resume: AUTO                        # can be Bool|"ERRORED_ONLY"|"all"|"AUTO"

algo_args:
  use_gae: True
  lambda: 0.99
  kl_coeff: 0.2
  batch_episode: 1
  num_sgd_iter: 5
  vf_loss_coeff: 1.0
  lr: 0.01
  entropy_coeff: 0.05
  clip_param: 0.3
  vf_clip_param: 10.0
  batch_mode: "complete_episodes"

  lr_scheduler:
  - - 0
    - 0.01
  - - 100000
    - 0.005
  - - 500000
    - 0.001
  - - 1000000
    - 0.0005
  - - 10000000
    - 0.0001

  entropy_coeff_scheduler:
  - - 0
    - 0.05
  - - 1000000
    - 0.03
  - - 10000000
    - 0.01
