env: macad

env_args:
  map_name: "Town01" # | "default" | "Homo" | "Town01" | "Town03" | "Town05" | "Town11"
  use_only_semantic: true
  use_only_camera: false

# Custom scenario support is currently removed

mask_flag: False
global_state_flag: False
opp_action_in_cc: False
agent_level_batch_update: False